- name: asdf git checkout
  ansible.builtin.git:
    repo: 'https://github.com/asdf-vm/asdf.git'
    dest: "~/.asdf"

- name: copy asdf.fish
  copy:
    src: asdf.fish
    dest: "~/.config/fish/conf.d/asdf.fish"
    mode: 0644

- name: Creates asdf directory
  file:
    path: ~/.config/fish/completions
    state: directory

- name: Create asdf symbolic link
  ansible.builtin.file:
    src: ~/.asdf/completions/asdf.fish
    dest: ~/.config/fish/completions/asdf.fish
    state: link

# nodejs

- name: asdf plugin add nodejs
  ansible.builtin.command: asdf plugin add nodejs

- ansible.builtin.command: asdf plugin update nodejs

- name: asdf install nodejs
  ansible.builtin.command: asdf install nodejs latest

- name: asdf global nodejs
  ansible.builtin.command: asdf global nodejs latest

- name: corepack
  ansible.builtin.command: ~/.asdf/shims/npm i --location=global corepack

- name: uninstall package managers
  ansible.builtin.command: ~/.asdf/shims/npm uninstall -g yarn pnpm

- name: pnpm
  ansible.builtin.command: ~/.asdf/shims/corepack enable pnpm
