- name: change user shell to fish 
  become: yes
  user:
    name: "{{ lookup('env','USER') }}"
    shell: /opt/homebrew/bin/fish

- name: install fisher
  ansible.builtin.command: fish -c 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher'
  environment:
    PATH: "/opt/homebrew/bin/:{{ ansible_env.PATH }}"

- name: install fzf
  ansible.builtin.command: fish -c 'fisher install jethrokuan/fzf'
  environment:
    PATH: "/opt/homebrew/bin/:{{ ansible_env.PATH }}"

- name: install fzf completion
  ansible.builtin.command: /opt/homebrew/opt/fzf/install
  environment:
    PATH: "/opt/homebrew/bin/:{{ ansible_env.PATH }}"

- name: install z
  ansible.builtin.command: fish -c 'fisher install jethrokuan/z'
  environment:
    PATH: "/opt/homebrew/bin/:{{ ansible_env.PATH }}"

- name: copy ls.fish
  copy:
    src: ls.fish
    dest: "~/.config/fish/functions/ls.fish"
    mode: 0644

- name: copy brew.fish
  copy:
    src: brew.fish
    dest: "~/.config/fish/conf.d/brew.fish"
    mode: 0644

- name: import asdf.yml
  import_tasks: asdf.yml
  environment:
    PATH: "/opt/homebrew/bin/:{{ ansible_env.PATH }}"
    