- name: persistent-apps
  community.general.osx_defaults:
    domain: com.apple.dock
    key: persistent-apps
    type: array
    value: []

- name: launchanim
  community.general.osx_defaults:
    domain: com.apple.dock
    key: launchanim
    type: bool
    value: false

- name:  autohide-delay
  community.general.osx_defaults:
    domain: com.apple.dock
    key:  autohide-delay
    type: float
    value: 0

- name: tilesize
  community.general.osx_defaults:
    domain: com.apple.dock
    key: tilesize
    type: float
    value: 32

- name: largesize
  community.general.osx_defaults:
    domain: com.apple.dock
    key: largesize
    type: float
    value: 64

- name: magnification
  community.general.osx_defaults:
    domain: com.apple.dock
    key: magnification
    type: bool
    value: true

- name: orientation
  community.general.osx_defaults:
    domain: com.apple.dock
    key: orientation
    type: string
    value: right

- name: killall Dock
  ansible.builtin.command: killall Dock
