## 別の型で設定されているとエラーになるので一度消す

- community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    state: absent
- community.general.osx_defaults:
    domain: NSGlobalDomain
    key: KeyRepeat
    type: int
    value: 3

- community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    state: absent
- community.general.osx_defaults:
    domain: NSGlobalDomain
    key: InitialKeyRepeat
    type: int
    value: 10

- name: NSAutomaticCapitalizationEnabled
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticCapitalizationEnabled
    type: bool
    value: false

- name: NSAutomaticSpellingCorrectionEnabled
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

- name: fnState
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.keyboard.fnState
    type: bool
    value: true

- name: ApplePressAndHoldEnabled
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: ApplePressAndHoldEnabled
    type: bool
    value: false