- name: TapToClick
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: com.apple.mouse.tapBehavior
    type: int
    value: 1

- community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    state: absent

- community.general.osx_defaults:
    domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true

- community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true

- name: NSTableViewDefaultSizeMode
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: NSTableViewDefaultSizeMode
    type: int
    value: 3

- name: ShowPercent
  community.general.osx_defaults:
    domain: com.apple.menuextra.battery
    key: ShowPercent
    type: string
    value: "YES"

- name: DSDontWriteNetworkStores
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true

- name: DSDontWriteUSBStores
  community.general.osx_defaults:
    domain: com.apple.desktopservices
    key: DSDontWriteUSBStores
    type: bool
    value: true

- name: FXPreferredViewStyle
  community.general.osx_defaults:
    domain: com.apple.finder
    key: FXPreferredViewStyle
    type: string
    value: "clmv"

- name: AppleInterfaceStyleSwitchesAutomatically
  community.general.osx_defaults:
    domain: NSGlobalDomain
    key: AppleInterfaceStyleSwitchesAutomatically
    type: bool
    value: true

- name: import dock.yml
  import_tasks: dock.yml

- name: import keyboard.yml
  import_tasks: keyboard.yml

- name: killall Finder
  ansible.builtin.command: killall Finder

- name: killall SystemUIServer
  ansible.builtin.command: killall SystemUIServer