- name: "install homebrew cask packages"
  community.general.homebrew_cask: 
    name: 
      - alfred
      - docker
      - dropbox
      - google-chrome
      - google-japanese-ime
      - iterm2
      - karabiner-elements
      - visual-studio-code
      - wavebox
      - clipy
      - aws-vault
      - bluesnooze
  
- name: Karabiner directory created
  file:
    path: "~/.config/karabiner"
    state: directory
    mode: 0775

- name: copy Karabiner settings
  copy:
    src: karabiner.json
    dest: "~/.config/karabiner/karabiner.json"
    mode: 0500
