- name: "install homebrew cask packages"
  community.general.homebrew_cask: 
    name: 
      - alfred
      - discord
      - docker
      - dropbox
      - google-chrome
      - google-japanese-ime
      - iterm2
      - karabiner-elements
      - visual-studio-code
      - wavebox
      - clipy
  
- name: copy Karabiner settings
  copy:
    src: karabiner.json
    dest: "~/.config/karabiner/karabiner.json"
    mode: 0500
